### ISSUE TITLE
how ```wget``` from ```download.oracle.com```?

### ISSUE THREAD

**Issue by gMan1990** [frekele/oracle-java#1]
Oracle url site http://download.oracle.com/otn-pub/java/jdk/...version

**Comment by frekele** [comment]
I did not understand your issue, could you be clearer?

**Comment by gMan1990** [comment]
how to download Oracle Java Binaries from ```http://download.oracle.com/otn-pub/java/jdk/...version``` use ```wget/curl```

**Comment by frekele** [comment]
You must access and download it here:
https://www.oracle.com/technetwork/java/javase/downloads/index.html

he artifacts available here are only for use in the [frekele/docker-java] compilation, due to the problems to obtain the direct download of the oracle site, many problems end up happening.

[frekele/docker-java]: https://github.com/frekele/docker-java

**Comment by frekele** [comment]
You must access and download it here:
https://www.oracle.com/technetwork/java/javase/downloads/index.html

The artifacts available here are only for use in the [frekele/docker-java] compilation, due to the problems to obtain the direct download of the oracle site, many problems end up happening.

[frekele/docker-java]: https://github.com/frekele/docker-java
